name: Wine Ubuntu CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deps
    run: |
      sudo dpkg --add-architecture i386 && sudo apt update
      sudo apt install -y libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libxcomposite-dev libxml++2.6-dev libxml2-dev libxslt1-dev libgnutls28-dev libsdl2-dev libsdl2-ttf-dev libglu1-mesa-dev libosmesa6-dev ocl-icd-dev ocl-icd-opencl-dev libcunit1-ncurses-dev libghc-ncurses-dev libpcap-dev libdbus-c++-dev libdbus-glib-1-dev libdbus-1-dev libsane-dev libv4l-dev libgphoto2-dev liblcms2-dev libpulse-dev libudev-dev libcapi20-dev libcups2-dev libfontconfig1-dev libxft-dev libgsm1-dev libgsmme-dev libkrb5-dev libtiff-dev libmpg123-dev libopenal-dev libvulkan-dev libldap2-dev libhbalinux-dev libfreetype6-dev libx11-dev libgstreamer-plugins-base1.0-dev mingw-w64 libgcrypt20-dev libusb-dev libusb-1.0-0-dev libjxr-dev libvkd3d-dev libfaudio-dev gnunet-gtk-dev libfaudio-dev libva-dev ccache flex mingw-w64 gcc-multilib gcc autoconf meson cmake make bison
      sudo apt-get install -y gcc-multilib
      sudo apt install -y libxcursor-dev:i386 
    - name: Wine 64
      run: |
       mkdir wine64
       cd wine64
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib" --with-x --without-oss --without-vkd3d --disable-tests --enable-win64 CFLAGS="${CFLAGS}" CC="gcc"
       make
    - name: Wine 32
      run: |
       cd Wine-Crossroads
       mkdir wine32
       cd wine32
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib32" --with-x --without-oss --without-vkd3d --disable-tests --with-wine64=../wine64 CFLAGS="${CFLAGS}" CC="ccache gcc"
       make
    - name: Finishing
      run: |
       cd Wine-Crossroads
       mkdir builds
       cd wine32
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib32" dlldir="${pkgdir}/lib32/wine" DESTDIR=builds/wine-crossroads-ubuntu install
       cd Wine-Crossroads
       cd wine64
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib" dlldir="${pkgdir}/lib/wine" DESTDIR=builds/wine-crossroads-ubuntu install
    - name: Archive the artifacts
      uses: actions/upload-artifact@v2
        
