name: Wine Ubuntu CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deps
    run: |
      sudo dpkg --add-architecture i386 && sudo apt update
      sudo apt install -y libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libxcomposite-dev libxml++2.6-dev libxml2-dev libxslt1-dev libgnutls28-dev libsdl2-dev libsdl2-ttf-dev libglu1-mesa-dev libosmesa6-dev ocl-icd-dev ocl-icd-opencl-dev libcunit1-ncurses-dev libghc-ncurses-dev libpcap-dev libdbus-c++-dev libdbus-glib-1-dev libdbus-1-dev libsane-dev libv4l-dev libgphoto2-dev liblcms2-dev libpulse-dev libudev-dev libcapi20-dev libcups2-dev libfontconfig1-dev libxft-dev libgsm1-dev libgsmme-dev libkrb5-dev libtiff-dev libmpg123-dev libopenal-dev libvulkan-dev libldap2-dev libhbalinux-dev libfreetype6-dev libx11-dev libgstreamer-plugins-base1.0-dev mingw-w64 libgcrypt20-dev libusb-dev libusb-1.0-0-dev libjxr-dev libvkd3d-dev libfaudio-dev gnunet-gtk-dev libfaudio-dev libva-dev ccache flex mingw-w64 gcc-multilib gcc autoconf meson cmake make bison
      sudo apt install -y libxcursor-dev:i386 libxrandr-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libxcomposite-dev:i386 ocl-icd-dev:i386 ocl-icd-opencl-dev:i386 libpcap-dev:i386 libdbus-c++-dev:i386 libglu1-mesa-dev:i386 libosmesa6-dev:i386 libdbus-1-dev:i386 libsane-dev:i386 libv4l-dev:i386 libgphoto2-dev:i386 liblcms2-dev:i386 libpulse-dev:i386 libudev-dev:i386 libcapi20-dev:i386 libfontconfig1-dev:i386 libgsm1-dev:i386 libkrb5-dev:i386 libmpg123-dev:i386 libopenal-dev:i386 libvulkan-dev:i386 libldap2-dev:i386 libgstreamer1.0-dev:i386 libfreetype6-dev:i386 libx11-dev:i386 libglib2.0-dev:i386 libibus-1.0-dev:i386 libglibmm-2.4-dev:i386 libfaudio-dev:i386 libva-dev:i386 libjpeg-dev:i386 libxxf86vm-dev:i386 libgnutls28-dev:i386 libncurses-dev:i386 libusb-dev:i386 libgtk-3-dev:i386 libcups2-dev:i386 libxml2-dev:i386 libxslt-dev:i386 libgstreamer-plugins-base1.0-dev:i386 gcc-8-multilib gcc-multilib lib32asan5 lib32atomic1 lib32gcc-8-dev lib32gcc1 lib32gomp1 lib32itm1 lib32mpx2 lib32quadmath0 lib32stdc++6 lib32ubsan1 libc6-dev-i386 libc6-dev-x32 libc6-i386 libc6-x32 libcups2-dev:i386 libcupsfilters-dev:i386 libcupsfilters1:i386 libcupsimage2:i386 libcupsimage2-dev:i386 libjbig-dev:i386 liblzma-dev:i386 libncurses5-dev:i386 libtiff-dev:i386 libtiff5-dev:i386 libtiffxx5:i386 libx32asan5 libx32atomic1 libx32gcc-8-dev libx32gcc1 libx32gomp1 libx32itm1 libx32quadmath0 libx32stdc++6 libx32ubsan1 libusb-1.0-0-dev:i386 libjxr-dev:i386 libvkd3d-dev:i386 libgstreamer-plugins-base1.0-dev:i386 libxml2-dev:i386 libxslt1-dev:i386
    - name: Wine 64
      run: |
       mkdir wine64
       cd wine64
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib" --with-x --without-oss --without-vkd3d --disable-tests --enable-win64 CFLAGS="${CFLAGS}" CC="gcc"
       make
    - name: Wine 32
      run: |
       cd Wine-Crossroads
       mkdir wine32
       cd wine32
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib32" --with-x --without-oss --without-vkd3d --disable-tests --with-wine64=../wine64 CFLAGS="${CFLAGS}" CC="ccache gcc"
       make
    - name: Finishing
      run: |
       cd Wine-Crossroads
       mkdir builds
       cd wine32
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib32" dlldir="${pkgdir}/lib32/wine" DESTDIR=builds/wine-crossroads-ubuntu install
       cd Wine-Crossroads
       cd wine64
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib" dlldir="${pkgdir}/lib/wine" DESTDIR=builds/wine-crossroads-ubuntu install
    - name: Archive the artifacts
      uses: actions/upload-artifact@v2
        
