name: Wine Ubuntu CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Wine 64
      run: |
       sudo dpkg --add-architecture i386 && sudo apt update
       mkdir wine64
       cd wine64
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib" --with-x --without-oss --without-vkd3d --disable-tests --enable-win64 CFLAGS="${CFLAGS}" CC="gcc"
       make
    - name: Wine 32
      run: |
       cd Wine-Crossroads
       mkdir wine32
       cd wine32
       ../configure --prefix="${pkgdir}" --libdir="${pkgdir}/lib32" --with-x --without-oss --without-vkd3d --disable-tests --with-wine64=../wine64 CFLAGS="${CFLAGS}" CC="ccache gcc"
       make
    - name: Finishing
      run: |
       cd Wine-Crossroads
       mkdir builds
       cd wine32
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib32" dlldir="${pkgdir}/lib32/wine" DESTDIR=builds/wine-crossroads-ubuntu install
       cd Wine-Crossroads
       cd wine64
       make STRIP=true prefix="${pkgdir}" libdir="${pkgdir}/lib" dlldir="${pkgdir}/lib/wine" DESTDIR=builds/wine-crossroads-ubuntu install
    - name: Archive the artifacts
      uses: actions/upload-artifact@v2
        
